/**
 * Convert `.npz` files generated by pinn_bdke into JSON by calling Python.
 *
 * We keep this logic server-side (API routes) because it shells out to Python.
 */

import { execFile } from 'child_process';
import { promisify } from 'util';
import path from 'path';
import fs from 'fs';

const execFileAsync = promisify(execFile);

const PROJECT_ROOT =
  process.env.PROJECT_ROOT || path.join(process.cwd(), '..');

function resolvePythonPath(): string {
  if (process.env.PYTHON_PATH && process.env.PYTHON_PATH.trim()) {
    return process.env.PYTHON_PATH.trim();
  }
  const venvPython = path.join(PROJECT_ROOT, '.venv', 'bin', 'python');
  if (fs.existsSync(venvPython)) return venvPython;
  return 'python';
}

const PYTHON_PATH = resolvePythonPath();

export async function npzToJson(npzPath: string): Promise<any> {
  const { stdout } = await execFileAsync(
    PYTHON_PATH,
    ['-m', 'pinn_bdke', 'utils', 'npz-to-json', '--input', npzPath],
    {
      cwd: PROJECT_ROOT,
      maxBuffer: 50 * 1024 * 1024,
    }
  );

  return JSON.parse(stdout);
}


