/* Minimal client-side i18n (EN/中文) with a header language toggle. */
'use client';

import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

export type Locale = 'en' | 'zh';

const DICT = {
  en: {
    appName: 'LearnableKGE',
    tagline: 'Visualize 2D/3D loss landscapes and training trajectories',
    navGenerate: 'Generate',
    navViewer: 'Viewer',
    panelGenerateTitle: 'Generate',
    inputSource: 'Input source',
    fromConfig: 'From Config',
    fromRun: 'From Run',
    configPath: 'Config path',
    runDir: 'Run directory',
    repoRelative: 'repo-relative',
    loadFromRunHint: 'Select a run directory to load landscape data from outputs/run_xxx/',
    noRunsFound: 'No runs found',
    loading: 'Loading…',
    optional: 'optional',
    runHint: 'If run is set, config is ignored; config + trajectory are extracted from the run folder.',
    mode: 'Generation Mode',
    mode2D: '2D Grid',
    mode3D: '3D Volume',
    grid: 'Grid',
    direction: 'Direction',
    generate: 'Generate',
    generating: 'Generating…',
    perfHint: 'Tip: 3D + grid=50 can be slow; try 30 first.',
    perfPresets: 'Quick Presets',
    presetFast: '⚡ Fast',
    presetStandard: '📊 Standard',
    presetHQ: '💎 High Quality',
    maxBatches: 'Max Batches',
    viewerTitle: 'Viewer',
    noDataTitle: 'No data yet',
    noDataDesc: 'Select a run directory to load landscape data.',
    loadingOverlay: 'Generating loss landscape…',
    historyTitle: 'History',
    historyHint: 'Load previously generated results (stored in DuckDB).',
    refresh: 'Refresh',
    load: 'Load',
    importTitle: 'Import',
    importHint: 'Import .npz files generated by loss landscape generation. Upload a file or scan a folder to automatically import all .npz files.',
    import: 'Import',
    uploadFile: 'Upload File',
    uploadHint: 'Upload a .npz file from your computer',
    selectFile: 'Select .npz file',
    fileSelected: 'File selected',
    scanFolder: 'Scan Folder',
    scanFolderHint: 'Scan a run directory (e.g., outputs/run_xxx) to automatically import all .npz files',
    folderPath: 'Folder path',
    scanAndImport: 'Scan & Import All',
    scanning: 'Scanning…',
    importing: 'Importing…',
    filesFound: 'files found',
    filesImported: 'files imported',
    viewMode: 'View Mode',
    view2D: '2D Heatmap',
    viewSurface: '3D Surface',
    viewSurfaceSlice: '3D Surface (γ slice)',
    viewSlice: '3D Slice',
    viewVolume: '3D Volume Render',
    gamma: 'γ',
    opacity: 'Opacity',
    step: 'Step',
    lowerIsBetter: 'Lower is better',
    view2DDesc: 'Shows loss in 2D (α, β). Good for understanding loss variations in two directions.',
    view3DSurfaceDesc: 'Shows loss as 3D surface (α, β, loss). Good for seeing the overall shape.',
    view3DSurfaceSliceDesc: 'Pick a γ slice of the 3D volume and view it as a 3D surface. Use the slider to move through slices.',
    view3DSliceDesc: 'Shows 2D slices of 3D volume at different γ values. Reveals how loss changes along the third dimension.',
    view3DVolumeDesc: 'Shows all slices blended together. Reveals 3D structure and high-loss regions.',
  },
  zh: {
    appName: 'LearnableKGE',
    tagline: '可视化 2D/3D loss landscape 与训练轨迹',
    navGenerate: '生成',
    navViewer: '预览',
    panelGenerateTitle: '生成',
    inputSource: '输入来源',
    fromConfig: '从 Config',
    fromRun: '从 Run',
    configPath: 'Config 路径',
    runDir: 'Run 目录',
    repoRelative: '相对仓库路径',
    loadFromRunHint: '选择一个 run 目录，从 outputs/run_xxx/ 加载 landscape 数据',
    noRunsFound: '未找到 run',
    loading: '加载中…',
    optional: '可选',
    runHint: '如果填写 run，会忽略 config，并从 run 目录自动提取 config + trajectory。',
    mode: '生成模式',
    mode2D: '2D 网格',
    mode3D: '3D 体积',
    grid: '网格',
    direction: '方向',
    generate: '生成',
    generating: '生成中…',
    perfHint: '提示：3D + grid=50 会比较慢，建议先用 30。',
    perfPresets: '快速预设',
    presetFast: '⚡ 快速',
    presetStandard: '📊 标准',
    presetHQ: '💎 高质量',
    maxBatches: '最大批次',
    viewerTitle: '预览',
    noDataTitle: '暂无数据',
    noDataDesc: '选择一个 run 目录以加载 landscape 数据。',
    loadingOverlay: '正在生成 loss landscape…',
    historyTitle: '历史记录',
    historyHint: '加载已生成结果（存储在 DuckDB）。',
    refresh: '刷新',
    load: '载入',
    importTitle: '导入',
    importHint: '导入 loss landscape 生成产生的 .npz 文件。可以上传单个文件或扫描文件夹自动导入所有 .npz 文件。',
    import: '导入',
    uploadFile: '上传文件',
    uploadHint: '从您的电脑上传 .npz 文件',
    selectFile: '选择 .npz 文件',
    fileSelected: '已选择文件',
    scanFolder: '扫描文件夹',
    scanFolderHint: '扫描 run 目录（如 outputs/run_xxx）自动导入所有 .npz 文件',
    folderPath: '文件夹路径',
    scanAndImport: '扫描并导入全部',
    scanning: '扫描中…',
    importing: '导入中…',
    filesFound: '个文件',
    filesImported: '个文件已导入',
    viewMode: '视图模式',
    view2D: '2D 热图',
    viewSurface: '3D 曲面',
    viewSurfaceSlice: '3D 曲面(γ切片)',
    viewSlice: '3D 切片',
    viewVolume: '3D 体渲染',
    gamma: 'γ',
    opacity: '透明度',
    step: '步长',
    lowerIsBetter: '越低越好',
    view2DDesc: '显示2D loss landscape (α, β)。适合理解两个方向上的loss变化。',
    view3DSurfaceDesc: '显示3D loss 曲面 (α, β, loss)，便于整体观察形状。',
    view3DSurfaceSliceDesc: '对3D体积按γ取切片，用3D曲面展示。拖动滑条在不同切片间切换。',
    view3DSliceDesc: '显示3D体积在不同γ值下的2D切片。揭示loss在第三个维度上的变化。',
    view3DVolumeDesc: '显示所有切片混合叠加。揭示3D结构和高loss区域。',
  },
} as const satisfies Record<Locale, Record<string, string>>;

type DictKey = keyof typeof DICT.en;
type Dict = Record<DictKey, string>;

const I18nCtx = createContext<{
  locale: Locale;
  setLocale: (l: Locale) => void;
  t: Dict;
} | null>(null);

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocale] = useState<Locale>('zh');

  useEffect(() => {
    const saved = typeof window !== 'undefined' ? window.localStorage.getItem('locale') : null;
    if (saved === 'en' || saved === 'zh') setLocale(saved);
  }, []);

  useEffect(() => {
    if (typeof window !== 'undefined') window.localStorage.setItem('locale', locale);
  }, [locale]);

  const value = useMemo(() => ({ locale, setLocale, t: DICT[locale] }), [locale]);
  return <I18nCtx.Provider value={value}>{children}</I18nCtx.Provider>;
}

export function useI18n() {
  const ctx = useContext(I18nCtx);
  if (!ctx) throw new Error('useI18n must be used within I18nProvider');
  return ctx;
}


