/**
 * API route to import an existing .npz (already generated by CLI) into DuckDB.
 */

import { NextRequest, NextResponse } from 'next/server';
import path from 'path';
import fs from 'fs';

import { npzToJson } from '@/lib/npz';
import { importNpzData } from '@/lib/import-npz';

export const dynamic = 'force-dynamic';

const PROJECT_ROOT = process.env.PROJECT_ROOT || path.join(process.cwd(), '..');

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const npzPathInput = String(body?.npzPath || '').trim();
    if (!npzPathInput) {
      return NextResponse.json({ error: 'npzPath is required' }, { status: 400 });
    }

    // Support repo-relative paths
    const npzPath = path.isAbsolute(npzPathInput)
      ? npzPathInput
      : path.join(PROJECT_ROOT, npzPathInput);

    if (!fs.existsSync(npzPath)) {
      return NextResponse.json({ error: `File not found: ${npzPathInput}` }, { status: 404 });
    }

    const data = await npzToJson(npzPath);
    const sourceLabel = `Imported from: ${path.basename(npzPathInput)}`;
    const id = await importNpzData(data, sourceLabel);

    return NextResponse.json({ success: true, id, data });
  } catch (error: any) {
    console.error('API error:', error);
    return NextResponse.json(
      { error: error.message || 'Internal server error' },
      { status: 500 }
    );
  }
}


